---
title: 'STAT 3302 Project Report'
author: "Edison Gu, "
date: "04/17/2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = TRUE)
library(tidyverse)
# library(readr)
# library(alr4)
library(GGally)
# library(broom)
# library(ggpubr)

# Source of the dataset: 
# https://www.kaggle.com/pavansubhasht/ibm-hr-analytics-attrition-dataset


tb <- read_csv("Employee_Attrition.csv")
```

## Data Preprocessing

```{r preprocessing}
education_level = c('Below College','College','Bachelor','Master','Doctor')
satisfaction_level = c('Low','Medium','High','Very High')
rating_level = c('Low','Good','Excellent','Outstanding')
balance_level = c('Bad','Good','Better','Best')

ea = tb %>% mutate(Attrition = ifelse(Attrition == "Yes", 1, 0),
                   Education = factor(case_when(
                           Education == 1 ~ 'Below College',
                           Education == 2 ~ 'College',
                           Education == 3 ~ 'Bachelor',
                           Education == 4 ~ 'Master',
                           Education == 5 ~ 'Doctor'),
                           levels = education_level),
                   EnvironmentSatisfaction = factor(case_when(
                           EnvironmentSatisfaction == 1 ~ 'Low',
                           EnvironmentSatisfaction == 2 ~ 'Medium',
                           EnvironmentSatisfaction == 3 ~ 'High',
                           EnvironmentSatisfaction == 4 ~ 'Very High'),
                           levels = satisfaction_level),
                   JobInvolvement = factor(case_when(
                           JobInvolvement == 1 ~ 'Low',
                           JobInvolvement == 2 ~ 'Medium',
                           JobInvolvement == 3 ~ 'High',
                           JobInvolvement == 4 ~ 'Very High'),
                           level = satisfaction_level),
                   JobSatisfaction = factor(case_when(
                           JobSatisfaction == 1 ~ 'Low',
                           JobSatisfaction == 2 ~ 'Medium',
                           JobSatisfaction == 3 ~ 'High',
                           JobSatisfaction == 4 ~ 'Very High'),
                           level = satisfaction_level),
                   PerformanceRating = factor(case_when(
                           PerformanceRating == 1 ~ 'Low',
                           PerformanceRating == 2 ~ 'Good',
                           PerformanceRating == 3 ~ 'Excellent',
                           PerformanceRating == 4 ~ 'Outstanding'),
                           level = rating_level),
                   RelationshipSatisfaction = factor(case_when(
                           RelationshipSatisfaction == 1 ~ 'Low',
                           RelationshipSatisfaction == 2 ~ 'Medium',
                           RelationshipSatisfaction == 3 ~ 'High',
                           RelationshipSatisfaction == 4 ~ 'Very High'),
                           level = satisfaction_level),
                   WorkLifeBalance = factor(case_when(
                           WorkLifeBalance == 1 ~ 'Bad',
                           WorkLifeBalance == 2 ~ 'Good',
                           WorkLifeBalance == 3 ~ 'Better',
                           WorkLifeBalance == 4 ~ 'Best'),
                           level = balance_level)) %>% 
        select(Attrition, Age, BusinessTravel, Department, DistanceFromHome,
               Education, EducationField, EnvironmentSatisfaction, Gender,
               JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, 
               MonthlyIncome, NumCompaniesWorked, OverTime, PercentSalaryHike,
               RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,
               TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole,
               YearsSinceLastPromotion, YearsWithCurrManager)

glimpse(ea)

```

## EDA

```{r EDA}
# ggpairs(ea)
for (i in seq_along(ea)){
        print(paste(i,")",colnames(ea)[i]))
        if(length(pull(unique(ea[i])))<30){
                 plot = ea %>% ggplot() + 
                         geom_bar(aes_string(colnames(ea)[i])) + 
                         coord_flip()
        } else {
                plot = ea %>% ggplot() + geom_density(aes_string(colnames(ea)[i]))
        }
        print(plot)
}
```

```{r}
tb %>% select(HourlyRate, DailyRate, MonthlyRate, MonthlyIncome) %>% 
        ggpairs()
```


```{r}
df = ea %>% select(MonthlyRate, MonthlyIncome)
par(mfrow=c(1,1))
matplot(t(df), type="l", xaxt="n", col="gray",
        xlab="Variable", ylab="Measurement")
axis(side=1, at=1:2, names(df))
points(1:2, colMeans(df), cex=1, pch=20, type="b", lwd=2)
```

```{r}
df = ea %>% select(YearsInCurrentRole, YearsWithCurrManager)
df %>% ggplot(aes(x=YearsInCurrentRole, y =YearsWithCurrManager))+geom_jitter()
df %>% ggplot(aes(x=YearsInCurrentRole, y =YearsWithCurrManager))+geom_point()
```

```{r}
par(mfrow=c(1,1))
matplot(t(df), type="l", xaxt="n", col="gray",
        xlab="Variable", ylab="Measurement")
axis(side=1, at=1:2, names(df))
points(1:2, colMeans(df), cex=1, pch=20, type="b", lwd=2)
```

```{r}
model1 = glm(data = ea, family = binomial,
             Attrition ~ Age + BusinessTravel + Department + DistanceFromHome +
                     EnvironmentSatisfaction + JobInvolvement + JobLevel + JobRole +
                     JobSatisfaction + MaritalStatus + MonthlyIncome + NumCompaniesWorked + 
                     OverTime + RelationshipSatisfaction + StockOptionLevel + TotalWorkingYears + 
                     TrainingTimesLastYear + WorkLifeBalance + YearsAtCompany + YearsInCurrentRole + 
                     YearsSinceLastPromotion + YearsWithCurrManager)

model1 %>% summary()
model1 %>% anova(test="Chisq")

```


```{r}
ea %>% select(Attrition, Age , YearsInCurrentRole) %>% 
        ggpairs()

```


```{r}
model2 = glm(data = ea, family = binomial,
             Attrition ~ JobRole)

model2 %>% summary()
model2 %>% anova(test="Chisq")

```






